CREATE TABLE Node (
    Id INT NOT NULL PRIMARY KEY IDENTITY, 
    Name VARCHAR(200) NOT NULL,
    IPv4 VARCHAR(200) NOT NULL,
    CpuCount INT NOT NULL DEFAULT 1, 
    MemoryTotalGb DECIMAL(15,2) NOT NULL DEFAULT 0,
    MemoryFreeGb DECIMAL(15,2) NOT NULL DEFAULT 0,
    DiskTotalGb DECIMAL(15,2) NOT NULL DEFAULT 0,
    DiskFreeGb DECIMAL(15,2) NOT NULL DEFAULT 0,
    LastContact DATETIME NOT NULL DEFAULT GETDATE()
);

